import { fileLog } from "../../helper-fns/file-logger";
import type { TRuleFn } from "../rule-types";

/**
 * Helper to extract just the filename from a path, handling both Unix and Windows paths
 */
function getFileName(filePath: string): string {
    // Normalize path separators to forward slashes
    const normalizedPath = filePath.replace(/\\/g, "/");
    // Get the last part (filename)
    const parts = normalizedPath.split("/");
    const fileName = parts[parts.length - 1];
    // Remove .ts extension
    return fileName.replace(/\.ts$/, "");
}

/**
 * Check if the file is a schema.better-auth.<dbname>.ts file
 */
function isBetterAuthSchema(filePath: string): boolean {
    const fileName = getFileName(filePath);
    return fileName.includes("schema.better-auth.");
}

/**
 * Rule: schema.better-auth.<dbname>.ts files are autogenerated and should not be edited directly
 * Users should edit auth.<dbname>.ts instead and run migrations
 */
export const ruleNotBetterAuthSchema: TRuleFn = async ({directory, filePath}) => {
    if (isBetterAuthSchema(filePath)) {
        const fileName = getFileName(filePath);
        
        // Extract dbname from the filename
        const dbName = fileName.replace("schema.better-auth.", "");
        
        fileLog("ruleNotBetterAuthSchema", "attempted to edit autogenerated file", fileName);
        return {
            error: 
                "AUTOGENERATED FILE. DO NOT EDIT. " +
                `The file ${fileName}.ts is automatically generated by better-auth CLI. ` +
                `To modify the better-auth schema, edit auth.${dbName}.ts and run migrations manually:\n\n` +
                "```bash\n" +
                `bunx --bun @better-auth/cli@latest generate --config=src/database/${dbName}/auth.${dbName}.ts --output=src/database/${dbName}/schema.better-auth.${dbName}.ts --yes\n` +
                `bunx drizzle-kit generate --config=drizzle.${dbName}.ts\n` +
                `bunx drizzle-kit migrate --config=drizzle.${dbName}.ts\n` +
                "```"
        };
    }
}