import { expect, test, describe } from "bun:test";
import { ruleNotBetterAuthSchema } from "./rule.database.not-better-auth-schema";

describe("ruleNotBetterAuthSchema", () => {
    const baseArgs = {
        directory: "/Users/omarezzat/Workspace/metaframework/bake",
        content: ""
    };

    test("should allow non-better-auth schema files", async () => {
        const result = await ruleNotBetterAuthSchema({
            ...baseArgs,
            filePath: "/Users/omarezzat/Workspace/metaframework/bake/src/database/users/schema.custom.users.ts"
        });

        expect(result).toBeUndefined();
    });

    test("should allow connection files", async () => {
        const result = await ruleNotBetterAuthSchema({
            ...baseArgs,
            filePath: "/Users/omarezzat/Workspace/metaframework/bake/src/database/users/conn.users.ts"
        });

        expect(result).toBeUndefined();
    });

    test("should allow auth files", async () => {
        const result = await ruleNotBetterAuthSchema({
            ...baseArgs,
            filePath: "/Users/omarezzat/Workspace/metaframework/bake/src/database/users/auth.users.ts"
        });

        expect(result).toBeUndefined();
    });

    test("should reject schema.better-auth files", async () => {
        const result = await ruleNotBetterAuthSchema({
            ...baseArgs,
            filePath: "/Users/omarezzat/Workspace/metaframework/bake/src/database/users/schema.better-auth.users.ts"
        });

        expect(result?.error).toContain("AUTOGENERATED FILE. DO NOT EDIT.");
        expect(result?.error).toContain("The file schema.better-auth.users.ts is automatically generated by better-auth CLI.");
        expect(result?.error).toContain("To modify better-auth schema, edit auth.users.ts and run migrations manually:");
        expect(result?.error).toContain("bunx --bun @better-auth/cli@latest generate --config=src/database/users/auth.users.ts --output=src/database/users/schema.better-auth.users.ts --yes");
        expect(result?.error).toContain("bunx drizzle-kit generate --config=drizzle.users.ts");
        expect(result?.error).toContain("bunx drizzle-kit migrate --config=drizzle.users.ts");
    });

    test("should reject schema.better-auth files with complex dbname", async () => {
        const result = await ruleNotBetterAuthSchema({
            ...baseArgs,
            filePath: "/Users/omarezzat/Workspace/metaframework/bake/src/database/user-profiles/schema.better-auth.user-profiles.ts"
        });

        expect(result?.error).toContain("AUTOGENERATED FILE. DO NOT EDIT.");
        expect(result?.error).toContain("The file schema.better-auth.user-profiles.ts is automatically generated by better-auth CLI.");
        expect(result?.error).toContain("To modify better-auth schema, edit auth.user-profiles.ts and run migrations manually:");
        expect(result?.error).toContain("bunx --bun @better-auth/cli@latest generate --config=src/database/user-profiles/auth.user-profiles.ts --output=src/database/user-profiles/schema.better-auth.user-profiles.ts --yes");
        expect(result?.error).toContain("bunx drizzle-kit generate --config=drizzle.user-profiles.ts");
        expect(result?.error).toContain("bunx drizzle-kit migrate --config=drizzle.user-profiles.ts");
    });

    test("should allow files outside database directory", async () => {
        const result = await ruleNotBetterAuthSchema({
            ...baseArgs,
            filePath: "/Users/omarezzat/Workspace/metaframework/bake/src/function/schema.better-auth.users.ts"
        });

        expect(result).toBeUndefined();
    });

    test("should handle Windows paths", async () => {
        const result = await ruleNotBetterAuthSchema({
            ...baseArgs,
            filePath: "C:\\Users\\omarezzat\\Workspace\\metaframework\\bake\\src\\database\\users\\schema.better-auth.users.ts"
        });

        expect(result?.error).toContain("AUTOGENERATED FILE. DO NOT EDIT.");
        expect(result?.error).toContain("The file schema.better-auth.users.ts is automatically generated by better-auth CLI.");
        expect(result?.error).toContain("To modify better-auth schema, edit auth.users.ts and run migrations manually:");
        expect(result?.error).toContain("bunx --bun @better-auth/cli@latest generate --config=src/database/users/auth.users.ts --output=src/database/users/schema.better-auth.users.ts --yes");
        expect(result?.error).toContain("bunx drizzle-kit generate --config=drizzle.users.ts");
        expect(result?.error).toContain("bunx drizzle-kit migrate --config=drizzle.users.ts");
    });
});