#!/usr/bin/env bun

import { mkdir, exists, unlink, rm } from 'node:fs/promises';
import { resolve, join } from 'node:path';
import { Database } from 'bun:sqlite';
import { $ } from 'bun';

// Global constant for database storage directory
const DATABASE_STORAGE_DIR = 'database-storage';

// Get database name from command line arguments
const dbName = process.argv[2];

if (!dbName) {
  console.error('Error: Database name is required');
  console.log('Usage: bun run .opencode/scripts/create-database.ts <db-name>');
  process.exit(1);
}

// Validate database name is URL-safe and a single word
const urlSafePattern = /^[a-zA-Z0-9_-]+$/;
if (!urlSafePattern.test(dbName)) {
  console.error('Error: Database name must be URL-safe and a single word');
  console.error('   Only alphanumeric characters, hyphens, and underscores are allowed');
  console.error(`   Got: "${dbName}"`);
  process.exit(1);
}

// Define paths
const projectRoot = resolve(import.meta.dir, '../..');
const databaseDir = join(projectRoot, DATABASE_STORAGE_DIR);
const dbFilePath = join(databaseDir, `${dbName}.sqlite`);
const drizzleConfigPath = join(projectRoot, `drizzle.${dbName}.ts`);
const dbSpecificDir = join(projectRoot, 'src/database', dbName);
const schemaPath = join(dbSpecificDir, `schema.custom.${dbName}.ts`);
const connPath = join(dbSpecificDir, `conn.${dbName}.ts`);

async function cleanup() {
  console.log('\nCleaning up...');
  try {
    if (await exists(dbFilePath)) await unlink(dbFilePath);
    if (await exists(drizzleConfigPath)) await unlink(drizzleConfigPath);
    if (await exists(schemaPath)) await unlink(schemaPath);
    if (await exists(connPath)) await unlink(connPath);
    if (await exists(dbSpecificDir)) await rm(dbSpecificDir, { recursive: true });
  } catch (e) {
    // Ignore cleanup errors
  }
}

try {
  // Check if database already exists
  const dbExists = await exists(dbFilePath);
  const configExists = await exists(drizzleConfigPath);
  const schemaExists = await exists(schemaPath);
  const connExists = await exists(connPath);

  if (dbExists || configExists || schemaExists || connExists) {
    console.error(`\nError: Database "${dbName}" already exists!`);
    if (dbExists) console.error(`   - Database file: ${dbFilePath}`);
    if (configExists) console.error(`   - Drizzle config: ${drizzleConfigPath}`);
    if (schemaExists) console.error(`   - Schema file: ${schemaPath}`);
    if (connExists) console.error(`   - Connection file: ${connPath}`);
    console.error('\nPlease choose a different name or delete the existing database files.');
    process.exit(1);
  }

  console.log(`\nCreating database: ${dbName}\n`);

  // Create database directory if it doesn't exist
  if (!await exists(databaseDir)) {
    await mkdir(databaseDir, { recursive: true });
    console.log('[1/7] Created database directory');
  } else {
    console.log('[1/7] Database directory exists');
  }

  // Create database-specific directory if it doesn't exist
  if (!await exists(dbSpecificDir)) {
    await mkdir(dbSpecificDir, { recursive: true });
    console.log('[2/7] Created database directory');
  } else {
    console.log('[2/7] Database directory exists');
  }

  // Create drizzle config file
  const drizzleConfig = `
/**
 * AUTOGENERATED FILE. DO NOT EDIT.
 * If you need to edit the schema, edit the schema files in src/database/${dbName}/schema.custom.${dbName}.ts and src/database/${dbName}/schema.auth.${dbName}.ts
 * and run \`bunx drizzle-kit generate --config=drizzle.${dbName}.ts\` to generate the migrations.
 * Finally run \`bunx drizzle-kit migrate --config=drizzle.${dbName}.ts\` to apply the migrations.
 */

import { defineConfig } from 'drizzle-kit';

export default defineConfig({
  dialect: 'sqlite',
  schema: './src/database/${dbName}/schema.*.ts',
  out: './drizzle/${dbName}',
  dbCredentials: {
    url: 'file:./${DATABASE_STORAGE_DIR}/${dbName}.sqlite',
  },
});
`;

  await Bun.write(drizzleConfigPath, drizzleConfig);
  console.log(`[3/7] Created Drizzle config: drizzle.${dbName}.ts`);

  const schemaContent = ``;
  await Bun.write(schemaPath, schemaContent);
  console.log(`[4/7] Created schema file: src/database/${dbName}/schema.custom.${dbName}.ts`);

  // Create connection file
  const connContent = `// AUTOGENERATED FILE. DO NOT EDIT.
import { drizzle } from 'drizzle-orm/bun-sqlite';
import { Database } from 'bun:sqlite';
import * as customSchema from './schema.custom.${dbName}.ts';
import { migrate } from 'drizzle-orm/bun-sqlite/migrator';

const schema = customSchema;

export const ${dbName}Sqlite = new Database('./${DATABASE_STORAGE_DIR}/${dbName}.sqlite');
${dbName}Sqlite.run('PRAGMA foreign_keys = ON');
${dbName}Sqlite.run('PRAGMA journal_mode = WAL');
${dbName}Sqlite.run('PRAGMA busy_timeout = 5000');
${dbName}Sqlite.run('PRAGMA synchronous = NORMAL');
${dbName}Sqlite.run('PRAGMA cache_size = 10000');
${dbName}Sqlite.run('PRAGMA temp_store = MEMORY');
${dbName}Sqlite.run('PRAGMA mmap_size = 268435456');
export const ${dbName}Db = drizzle({ client: ${dbName}Sqlite, schema });


/**
 * Creates a new inmemory database for testing.
 * With schema and migrations applied.
 */
export function createTesting${dbName.charAt(0).toUpperCase() + dbName.slice(1)}Db(): typeof ${dbName}Db {
    const memoryDb = new Database(':memory:')
    memoryDb.run('PRAGMA foreign_keys = ON');
    memoryDb.run('PRAGMA journal_mode = WAL');
    memoryDb.run('PRAGMA busy_timeout = 5000');
    memoryDb.run('PRAGMA synchronous = NORMAL');
    memoryDb.run('PRAGMA cache_size = 10000');
    memoryDb.run('PRAGMA temp_store = MEMORY');
    memoryDb.run('PRAGMA mmap_size = 268435456');
    const ${dbName}TestingDb = drizzle({ client: memoryDb, schema });
    migrate(${dbName}TestingDb, { migrationsFolder: './drizzle/${dbName}' });
    return ${dbName}TestingDb;
}
`;
  await Bun.write(connPath, connContent);
  console.log(`[5/7] Created connection file: src/database/${dbName}/conn.${dbName}.ts`);

  // Create SQLite database file first
  const db = new Database(dbFilePath, { create: true });
  db.close();
  console.log(`[6/7] Created SQLite database: ${DATABASE_STORAGE_DIR}/${dbName}.sqlite`);

  // Push schema directly to database (no migrations needed for initial setup)
  console.log('[7/7] Pushing schema to database...', `Run: bunx drizzle-kit push --config=drizzle.${dbName}.ts`);
  const pushResult = await $`bunx drizzle-kit push --config=drizzle.${dbName}.ts`.text();

  if (pushResult.includes('error') || pushResult.includes('Error')) {
    console.error('Error: Failed to push schema');
    console.error(pushResult);
    await cleanup();
    process.exit(1);
  }
  console.log('[7/7] Schema pushed successfully');

  console.log('\n==============================================');
  console.log('Database setup complete!');
  console.log('==============================================\n');
  console.log('Created files:');
  console.log(`  - ${DATABASE_STORAGE_DIR}/${dbName}.sqlite`);
  console.log(`  - drizzle.${dbName}.ts`);
  console.log(`  - src/database/${dbName}/schema.${dbName}.ts`);
  console.log(`  - src/database/${dbName}/conn.${dbName}.ts`);
  console.log('\nNext steps:');
  console.log(`  1. Edit your schema: src/database/${dbName}/schema.${dbName}.ts`);
  console.log(`  2. Push schema changes: bunx drizzle-kit push --config=drizzle.${dbName}.ts`);
  console.log(`  3. Import the database connection: import { ${dbName}Db } from './src/database/${dbName}/conn.${dbName}'`);
  console.log(`\n  Note: Using 'push' for instant schema updates (no migrations)`);
  console.log(`  For migrations workflow, use: generate & migrate commands\n`);

} catch (error) {
  console.error('\nError creating database:', error);
  await cleanup();
  process.exit(1);
}