#!/usr/bin/env bun
import { $ } from "bun";
import path from "node:path";
import { getDatabaseVariableNames } from "../helper-fns/get-db-names";
import { addAuthToRouter } from "../helper-fns/add-auth-to-router";
import { existsSync } from "fs";

const dbName = process.argv[2];
const projectRoot = path.resolve(import.meta.dir, '../../');
const dbNames = await getDatabaseVariableNames(projectRoot).then(names => names.map(n => n.substring(0, n.length - 2)));

if (!dbName) {
  console.error(`Usage: bun run install-better-auth.ts <db-name> \n Must be one of: ${dbNames.join(', ')}`);
  process.exit(1);
}

if (!dbNames.includes(dbName)) {
  console.error(`Database ${dbName} not found. Must be one of: ${dbNames.join(', ')}`);
  process.exit(1);
}

// Ensure database directory exists
const dbDir = path.join(projectRoot, "src/database", dbName);
await mkdir(dbDir, { recursive: true });

// Create connection file first
const connFileContent = `import { drizzle } from "drizzle-orm/bun-sqlite";
import { Database } from "bun:sqlite";
import * as customSchema from "./schema.custom.${dbName}.ts";

const sqlite = new Database("./database-storage/${dbName}.sqlite");
export const ${dbName}Db = drizzle(sqlite, { schema: customSchema });

// Export: database instance and schema
export { customSchema };
export type ${dbName}Db = typeof ${dbName}Db;
`;

await writeFile(path.join(dbDir, `conn.${dbName}.ts`), connFileContent, "utf8");
console.log(`Created connection file: src/database/${dbName}/conn.${dbName}.ts`);

// Create custom schema file
const customSchemaContent = `// Custom schema for ${dbName} database
import { sqliteTable, text, integer, index } from "drizzle-orm/sqlite-core";

// Add your custom tables here

// export const mytable = sqliteTable("mytable", {
//   id: text("id").primaryKey(),
//   name: text("name").notNull(),
// });
`;

await writeFile(path.join(dbDir, `schema.custom.${dbName}.ts`), customSchemaContent, "utf8");
console.log(`Created custom schema file: src/database/${dbName}/schema.custom.${dbName}.ts`);

const authServerFile = `// https://www.better-auth.com/docs/basic-usage
import { betterAuth } from "better-auth";
import { drizzleAdapter } from "better-auth/adapters/drizzle";
import { ${dbName}Db } from "./conn.${dbName}.ts";

export const auth = betterAuth({
  database: drizzleAdapter(${dbName}Db, {
    provider: "sqlite",
  }), 
  emailAndPassword: {
    enabled: true,
  },
});
`;

await writeFile(path.join(dbDir, `auth.${dbName}.ts`), authServerFile, "utf8");
console.log(`Created auth file: src/database/${dbName}/auth.${dbName}.ts`);

// Run drizzle-kit generate
const drizzleConfig = `drizzle.${dbName}.ts`;

// Generate better-auth schema with temporary filename
const tempSchemaFile = path.join(projectRoot, "src/database", dbName, `schema.auth.${dbName}.ts`);
const finalSchemaFile = path.join(projectRoot, "src/database", dbName, `schema.better-auth.${dbName}.ts`);

await $`bunx --bun @better-auth/cli@latest generate --config=src/database/${dbName}/auth.${dbName}.ts --output=${tempSchemaFile} --yes`.cwd(projectRoot);

// Rename the file from schema.auth to schema.better-auth
import { rename } from "node:fs/promises";
await rename(tempSchemaFile, finalSchemaFile);
console.log(`Renamed schema file to: src/database/${dbName}/schema.better-auth.${dbName}.ts`);

await $`bunx drizzle-kit generate --config=${drizzleConfig}`.cwd(projectRoot);
await $`bunx drizzle-kit migrate --config=${drizzleConfig}`.cwd(projectRoot);

// Add autogeneration warning header to the schema file
import { readFile, writeFile, mkdir } from "node:fs/promises";

let schemaContent = await readFile(finalSchemaFile, "utf8");

const warningHeader = `/**
 * AUTOGENERATED FILE. DO NOT EDIT.
 * 
 * This file is automatically generated by better-auth CLI.
 * To modify the better-auth schema, edit auth.${dbName}.ts and run migrations manually:
 * 
 * \`\`\`bash
 * bunx --bun @better-auth/cli@latest generate --config=src/database/${dbName}/auth.${dbName}.ts --output=src/database/${dbName}/schema.better-auth.${dbName}.ts --yes
 * bunx drizzle-kit generate --config=drizzle.${dbName}.ts
 * bunx drizzle-kit migrate --config=drizzle.${dbName}.ts
 * \`\`\`
 * 
 * If you want to edit other tables, edit the schema.custom.${dbName}.ts file instead.
 */

`;

schemaContent = warningHeader + schemaContent;
await writeFile(finalSchemaFile, schemaContent, "utf8");
console.log(`Added autogeneration warning to schema file`);

// After running auth codegen, also update the connection file to combine authSchema with customSchema.
const connFile = path.join(
  projectRoot,
  "src/database",
  dbName,
  `conn.${dbName}.ts`
);

let connContent = await readFile(connFile, "utf8");

// Update the connection file to include both auth and custom schemas
const updatedConnContent = `import { drizzle } from "drizzle-orm/bun-sqlite";
import { Database } from "bun:sqlite";
import * as customSchema from "./schema.custom.${dbName}.ts";
import * as authSchema from "./schema.better-auth.${dbName}.ts";

const sqlite = new Database("./database-storage/${dbName}.sqlite");
export const ${dbName}Db = drizzle(sqlite, { schema: { ...authSchema, ...customSchema } });

// Export: database instance and schemas
export { customSchema, authSchema };
export type ${dbName}Db = typeof ${dbName}Db;
`;

await writeFile(connFile, updatedConnContent, "utf8");
console.log(`Updated "${connFile}": combined authSchema and customSchema.`);

// Create Elysia auth plugin with macro for session resolution
const pluginContent = `import { Elysia } from "elysia";
import { auth } from "./auth.${dbName}";

/**
 * Elysia plugin for ${dbName} authentication
 *
 * Provides { auth: true } macro for protected routes.
 * Use this plugin in child API files to get { user, session } types.
 *
 * Note: auth.handler is mounted separately in api-router.ts to expose /api/auth/* endpoints.
 *
 * Usage:
 * \`\`\`typescript
 * import { ${dbName}AuthPlugin } from "@/src/database/${dbName}/plugin.auth.${dbName}";
 *
 * export default new Elysia({ prefix: '/api/foo' })
 *   .use(${dbName}AuthPlugin)
 *   .get('/me', ({ user }) => user, { auth: true })  // Protected route
 *   .get('/public', () => 'hello')                   // Public route
 * \`\`\`
 */
export const ${dbName}AuthPlugin = new Elysia({ name: "auth-${dbName}-plugin" })
  .macro({
    auth: {
      async resolve({ status, request: { headers } }) {
        const session = await auth.api.getSession({ headers });
        if (!session) return status(401);
        return { user: session.user, session: session.session };
      },
    },
  });

// Type inference from Better Auth
export type TAuthSession = typeof auth.$Infer.Session;
export type TAuthUser = typeof auth.$Infer.Session.user;
`;

const pluginFile = path.join(dbDir, `plugin.auth.${dbName}.ts`);
await writeFile(pluginFile, pluginContent, "utf8");
console.log(`Created auth plugin: src/database/${dbName}/plugin.auth.${dbName}.ts`);

// Add auth handler to router
console.log('\n🔧 Adding auth handler to router...');
const indexTsxPath = path.join(projectRoot, "src/index.tsx");
const indexTsPath = path.join(projectRoot, "src/index.ts");

let indexPath: string | null = null;
if (existsSync(indexTsxPath)) {
  indexPath = indexTsxPath;
} else if (existsSync(indexTsPath)) {
  indexPath = indexTsPath;
}

if (indexPath) {
  const result = addAuthToRouter(indexPath, dbName);
  if (result.success) {
    console.log(`✅ ${result.message}`);
  } else {
    // Add comment at top of file indicating this better-auth instance is not added
    const commentToAdd = `// NOTE: better-auth for database "${dbName}" is installed but not added to router.\n// ${result.message}\n// Import: import { auth } from "@/src/database/${dbName}/auth.${dbName}";\n// Mount in api-router.ts: .mount(auth.handler)\n\n`;

    let indexContent = await readFile(indexPath, "utf8");

    // Check if comment already exists
    if (!indexContent.includes(`better-auth for database "${dbName}"`)) {
      indexContent = commentToAdd + indexContent;
      await writeFile(indexPath, indexContent, "utf8");
      console.log(`⚠️  ${result.message}`);
      console.log(`📝 Added comment to ${path.basename(indexPath)} with manual setup instructions`);
    } else {
      console.log(`ℹ️  Comment already exists in ${path.basename(indexPath)}`);
    }
  }
} else {
  console.log('⚠️  src/index.tsx or src/index.ts not found, skipping router update');
  console.log('📝 Please manually add the following to api-router.ts:');
  console.log(`   Import: import { auth } from "@/src/database/${dbName}/auth.${dbName}";`);
  console.log(`   Mount: .mount(auth.handler)`);
}

console.log('\n✅ Better-auth installation completed!');
console.log('\n📋 Files created/updated:');
console.log(`   - src/database/${dbName}/auth.${dbName}.ts`);
console.log(`   - src/database/${dbName}/schema.better-auth.${dbName}.ts`);
console.log(`   - src/database/${dbName}/conn.${dbName}.ts (updated)`);
console.log(`   - src/database/${dbName}/plugin.auth.${dbName}.ts`);
console.log(`   - src/api-router.ts (.mount(auth.handler) added)`);

console.log('\n📖 Two-part setup:');
console.log('');
console.log('   1. api-router.ts - Exposes /api/auth/* endpoints (login, signup, etc.)');
console.log(`      .mount(auth.handler)  // Already added`);
console.log('');
console.log('   2. Child API files - Use plugin for { user, session } types:');
console.log(`      import { ${dbName}AuthPlugin } from "@/src/database/${dbName}/plugin.auth.${dbName}";`);
console.log('');
console.log('      export default new Elysia({ prefix: "/api/foo" })');
console.log(`        .use(${dbName}AuthPlugin)`);
console.log('        .get("/me", ({ user }) => user, { auth: true })  // Protected');
console.log('        .get("/public", () => "hello")                   // Public');

